# Generated by Django 3.2.12 on 2022-05-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('brand', 'Brand'), ('regular', 'Regular')], default='Regular', max_length=32),
        ),
    ]
