# Generated by Django 3.2.12 on 2022-08-14 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 9, 23, 40, 162068)),
        ),
    ]
