# Generated by Django 3.2.12 on 2022-08-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('brand', 'Brand')], default='Regular', max_length=32),
        ),
    ]
