# Generated by Django 3.2.12 on 2022-08-14 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_postviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 9, 22, 27, 943919)),
        ),
    ]
